const mockdata = {
  stores: [
    {
      storeName: "Spicy BBQ Chicken",
      foodItems: [
        {
          name: "Margherita Pizza",
          rating: 4.5,
          deals: "20% off on your first order",
          deliveryTime: "30 mins",
          price: "$12",
          image: "image1.jpeg",
        },
        {
          name: "Pepperoni Pizza",
          rating: 4.7,
          deals: "Buy one, get one free",
          deliveryTime: "35 mins",
          price: "$15",
          image: "image2.jpg",
        },
        {
          name: "BBQ Chicken Pizza",
          rating: 4.6,
          deals: "Free garlic bread with purchase",
          deliveryTime: "30 mins",
          price: "$16",
          image: "image3.jpg",
        },
        {
          name: "Veggie Supreme",
          rating: 4.3,
          deals: "Free delivery",
          deliveryTime: "25 mins",
          price: "$14",
          image: "image4.jpg",
        },
        {
          name: "Four Cheese Pizza",
          rating: 4.4,
          deals: "15% off for students",
          deliveryTime: "30 mins",
          price: "$18",
          image: "image5.jpg",
        },
        {
          name: "Hawaiian Pizza",
          rating: 4.2,
          deals: "Free soda with purchase",
          deliveryTime: "35 mins",
          price: "$17",
          image: "image6.jpg",
        },
        {
          name: "Buffalo Chicken Pizza",
          rating: 4.6,
          deals: "10% cashback on order",
          deliveryTime: "40 mins",
          price: "$16",
          image: "image7.jpg",
        },
        {
          name: "Classic Cheese Pizza",
          rating: 4.1,
          deals: "Free extra cheese",
          deliveryTime: "20 mins",
          price: "$11",
          image: "image8.jpg",
        },
      ],
    },
    {
      storeName: "Margherita Pizza",
      foodItems: [
        {
          name: "Apple Fritter",
          rating: 4.8,
          deals: "Buy 2 get 1 free",
          deliveryTime: "20 mins",
          price: "$5",
          image: "image9.jpg",
        },
        {
          name: "Banana Fritter",
          rating: 4.6,
          deals: "10% off on weekends",
          deliveryTime: "25 mins",
          price: "$6",
          image: "image10.jpg",
        },
        {
          name: "Blueberry Fritter",
          rating: 4.7,
          deals: "Free coffee with order",
          deliveryTime: "20 mins",
          price: "$7",
          image: "image11.jpg",
        },
        {
          name: "Chocolate Fritter",
          rating: 4.5,
          deals: "Free delivery for orders above $15",
          deliveryTime: "15 mins",
          price: "$6",
          image: "image1.jpeg",
        },
        {
          name: "Pumpkin Fritter",
          rating: 4.3,
          deals: "15% off for members",
          deliveryTime: "20 mins",
          price: "$6",
          image: "image2.jpg",
        },
        {
          name: "Cherry Fritter",
          rating: 4.4,
          deals: "Free topping of choice",
          deliveryTime: "25 mins",
          price: "$7",
          image: "image3.jpg",
        },
        {
          name: "Cinnamon Fritter",
          rating: 4.2,
          deals: "Free delivery for orders above $10",
          deliveryTime: "20 mins",
          price: "$5",
          image: "image4.jpg",
        },
        {
          name: "Mixed Berry Fritter",
          rating: 4.5,
          deals: "10% cashback on all orders",
          deliveryTime: "30 mins",
          price: "$8",
          image: "image5.jpg",
        },
      ],
    },
    {
      storeName: "Sushi Platter",
      foodItems: [
        {
          name: "Grilled Chicken Sandwich",
          rating: 4.7,
          deals: "Free fries with order",
          deliveryTime: "30 mins",
          price: "$10",
          image: "image6.jpg",
        },
        {
          name: "Veggie Burger",
          rating: 4.5,
          deals: "20% off on orders above $20",
          deliveryTime: "25 mins",
          price: "$9",
          image: "image7.jpg",
        },
        {
          name: "Fish and Chips",
          rating: 4.6,
          deals: "Buy one, get one half off",
          deliveryTime: "35 mins",
          price: "$12",
          image: "image8.jpg",
        },
        {
          name: "Chicken Wrap",
          rating: 4.4,
          deals: "Free drink with order",
          deliveryTime: "20 mins",
          price: "$8",
          image: "image9.jpg",
        },
        {
          name: "Shrimp Tacos",
          rating: 4.8,
          deals: "Buy 2, get 1 free",
          deliveryTime: "30 mins",
          price: "$11",
          image: "image10.jpg",
        },
        {
          name: "Pulled Pork Sandwich",
          rating: 4.7,
          deals: "10% off on first order",
          deliveryTime: "25 mins",
          price: "$10",
          image: "image11.jpg",
        },
        {
          name: "Buffalo Wings",
          rating: 4.5,
          deals: "Free extra sauce",
          deliveryTime: "30 mins",
          price: "$9",
          image: "image1.jpeg",
        },
        {
          name: "Caesar Salad",
          rating: 4.4,
          deals: "Free garlic bread with salad",
          deliveryTime: "20 mins",
          price: "$7",
          image: "image2.jpg",
        },
      ],
    },
    {
      storeName: "Caesar Salad",
      foodItems: [
        {
          name: "Masala Chai",
          rating: 4.9,
          deals: "Buy 1 get 1 free",
          deliveryTime: "15 mins",
          price: "$2",
          image: "image3.jpg",
        },
        {
          name: "Irani Tea",
          rating: 4.8,
          deals: "Free cookie with order",
          deliveryTime: "15 mins",
          price: "$3",
          image: "image4.jpg",
        },
        {
          name: "Bun Maska",
          rating: 4.7,
          deals: "Free tea with every bun maska",
          deliveryTime: "20 mins",
          price: "$2",
          image: "image5.jpg",
        },
        {
          name: "Samosa",
          rating: 4.6,
          deals: "Free chutney with every order",
          deliveryTime: "20 mins",
          price: "$2",
          image: "image6.jpg",
        },
        {
          name: "Puff Pastry",
          rating: 4.5,
          deals: "20% off on all pastries",
          deliveryTime: "25 mins",
          price: "$4",
          image: "image7.jpg",
        },
        {
          name: "Chicken Roll",
          rating: 4.6,
          deals: "Buy 2 get 1 free",
          deliveryTime: "20 mins",
          price: "$5",
          image: "image8.jpg",
        },
        {
          name: "Mutton Keema",
          rating: 4.7,
          deals: "Free drink with order",
          deliveryTime: "30 mins",
          price: "$8",
          image: "image9.jpg",
        },
        {
          name: "Egg Bhurji",
          rating: 4.6,
          deals: "10% off on your next order",
          deliveryTime: "15 mins",
          price: "$5",
          image: "image10.jpg",
        },
      ],
    },
    {
      storeName: "Tandoori Chicken",
      foodItems: [
        {
          name: "Chocolate Cake",
          rating: 4.9,
          deals: "20% off for first-time customers",
          deliveryTime: "30 mins",
          price: "$15",
          image: "image11.jpg",
        },
        {
          name: "Cheesecake",
          rating: 4.8,
          deals: "Buy 1, get 1 free",
          deliveryTime: "35 mins",
          price: "$14",
          image: "image1.jpeg",
        },
        {
          name: "Tiramisu",
          rating: 4.6,
          deals: "Free dessert with orders over $30",
          deliveryTime: "40 mins",
          price: "$16",
          image: "image2.jpg",
        },
        {
          name: "Apple Pie",
          rating: 4.5,
          deals: "10% off on next order",
          deliveryTime: "25 mins",
          price: "$12",
          image: "image3.jpg",
        },
        {
          name: "Brownies",
          rating: 4.7,
          deals: "Free delivery for orders above $20",
          deliveryTime: "30 mins",
          price: "$10",
          image: "image4.jpg",
        },
        {
          name: "Cupcakes",
          rating: 4.8,
          deals: "10% off on first order",
          deliveryTime: "20 mins",
          price: "$5",
          image: "image5.jpg",
        },
        {
          name: "Pancakes",
          rating: 4.6,
          deals: "Free syrup with every order",
          deliveryTime: "15 mins",
          price: "$8",
          image: "image6.jpg",
        },
        {
          name: "Ice Cream",
          rating: 4.5,
          deals: "20% off on all flavors",
          deliveryTime: "30 mins",
          price: "$7",
          image: "image7.jpg",
        },
      ],
    },
    {
      storeName: "Beef Burger",
      foodItems: [
        {
          name: "Nachos",
          rating: 4.7,
          deals: "Free cheese dip with order",
          deliveryTime: "25 mins",
          price: "$6",
          image: "image8.jpg",
        },
        {
          name: "Popcorn",
          rating: 4.6,
          deals: "Buy 1, get 1 free",
          deliveryTime: "15 mins",
          price: "$5",
          image: "image9.jpg",
        },
        {
          name: "Potato Wedges",
          rating: 4.5,
          deals: "10% off on all orders",
          deliveryTime: "20 mins",
          price: "$4",
          image: "image10.jpg",
        },
        {
          name: "Spring Rolls",
          rating: 4.8,
          deals: "Free dipping sauce with order",
          deliveryTime: "30 mins",
          price: "$7",
          image: "image11.jpg",
        },
        {
          name: "Stuffed Peppers",
          rating: 4.5,
          deals: "Free drink with order",
          deliveryTime: "25 mins",
          price: "$8",
          image: "image1.jpeg",
        },
        {
          name: "Onion Rings",
          rating: 4.4,
          deals: "Free delivery for orders above $15",
          deliveryTime: "20 mins",
          price: "$6",
          image: "image2.jpg",
        },
        {
          name: "Cheese Sticks",
          rating: 4.6,
          deals: "10% cashback on order",
          deliveryTime: "30 mins",
          price: "$5",
          image: "image3.jpg",
        },
        {
          name: "Garlic Bread",
          rating: 4.3,
          deals: "20% off on orders above $25",
          deliveryTime: "30 mins",
          price: "$4",
          image: "image4.jpg",
        },
      ],
    },
    {
      storeName: "French Fries",
      foodItems: [
        {
          name: "Quinoa Salad",
          rating: 4.7,
          deals: "Free drink with every salad",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image5.jpg",
        },
        {
          name: "Grilled Vegetable Wrap",
          rating: 4.8,
          deals: "10% off for first order",
          deliveryTime: "25 mins",
          price: "$9",
          image: "image6.jpg",
        },
        {
          name: "Chickpea Salad",
          rating: 4.6,
          deals: "Free extra topping",
          deliveryTime: "15 mins",
          price: "$8",
          image: "image7.jpg",
        },
        {
          name: "Zucchini Noodles",
          rating: 4.5,
          deals: "Free delivery for orders above $20",
          deliveryTime: "30 mins",
          price: "$11",
          image: "image8.jpg",
        },
        {
          name: "Fruit Bowl",
          rating: 4.9,
          deals: "20% off on all fruit bowls",
          deliveryTime: "20 mins",
          price: "$7",
          image: "image9.jpg",
        },
        {
          name: "Vegan Burger",
          rating: 4.6,
          deals: "Buy 1, get 1 free",
          deliveryTime: "30 mins",
          price: "$10",
          image: "image10.jpg",
        },
        {
          name: "Almond Milkshake",
          rating: 4.4,
          deals: "Free topping of choice",
          deliveryTime: "15 mins",
          price: "$5",
          image: "image11.jpg",
        },
        {
          name: "Coconut Chia Pudding",
          rating: 4.8,
          deals: "10% off on orders above $15",
          deliveryTime: "25 mins",
          price: "$6",
          image: "image1.jpeg",
        },
      ],
    },
    {
      storeName: "Pad Thai",
      foodItems: [
        {
          name: "Masala Chai",
          rating: 4.9,
          deals: "Buy 1 get 1 free",
          deliveryTime: "15 mins",
          price: "$2",
          image: "image3.jpg",
        },
        {
          name: "Irani Tea",
          rating: 4.8,
          deals: "Free cookie with order",
          deliveryTime: "15 mins",
          price: "$3",
          image: "image4.jpg",
        },
        {
          name: "Bun Maska",
          rating: 4.7,
          deals: "Free tea with every bun maska",
          deliveryTime: "20 mins",
          price: "$2",
          image: "image5.jpg",
        },
        {
          name: "Samosa",
          rating: 4.6,
          deals: "Free chutney with every order",
          deliveryTime: "20 mins",
          price: "$2",
          image: "image6.jpg",
        },
        {
          name: "Puff Pastry",
          rating: 4.5,
          deals: "20% off on all pastries",
          deliveryTime: "25 mins",
          price: "$4",
          image: "image7.jpg",
        },
        {
          name: "Chicken Roll",
          rating: 4.6,
          deals: "Buy 2 get 1 free",
          deliveryTime: "20 mins",
          price: "$5",
          image: "image8.jpg",
        },
        {
          name: "Mutton Keema",
          rating: 4.7,
          deals: "Free drink with order",
          deliveryTime: "30 mins",
          price: "$8",
          image: "image9.jpg",
        },
        {
          name: "Egg Bhurji",
          rating: 4.6,
          deals: "10% off on your next order",
          deliveryTime: "15 mins",
          price: "$5",
          image: "image10.jpg",
        },
      ],
    },
    {
      storeName: "Pepperoni Pizza",
      foodItems: [
        {
          name: "Pepperoni Pizza",
          rating: 4.9,
          deals: "Buy one, get one free",
          deliveryTime: "30 mins",
          price: "$12",
          image: "image1.jpeg",
        },
        {
          name: "Vegetarian Pizza",
          rating: 4.8,
          deals: "15% off on your first order",
          deliveryTime: "30 mins",
          price: "$11",
          image: "image2.jpg",
        },
        {
          name: "BBQ Chicken Pizza",
          rating: 4.7,
          deals: "Free soda with pizza",
          deliveryTime: "30 mins",
          price: "$13",
          image: "image3.jpg",
        },
        {
          name: "Mushroom Pizza",
          rating: 4.6,
          deals: "Free garlic bread with pizza",
          deliveryTime: "30 mins",
          price: "$10",
          image: "image4.jpg",
        },
        {
          name: "Hawaiian Pizza",
          rating: 4.5,
          deals: "10% off on weekends",
          deliveryTime: "30 mins",
          price: "$12",
          image: "image5.jpg",
        },
      ],
    },
    {
      storeName: "Chicken Kebab",
      foodItems: [
        {
          name: "Chicken Kebab",
          rating: 4.7,
          deals: "Free drink with kebab",
          deliveryTime: "25 mins",
          price: "$10",
          image: "image6.jpg",
        },
        {
          name: "Spicy Chicken Kebab",
          rating: 4.6,
          deals: "10% off on your first order",
          deliveryTime: "25 mins",
          price: "$11",
          image: "image7.jpg",
        },
        {
          name: "Grilled Chicken Kebab",
          rating: 4.8,
          deals: "Free side with kebab",
          deliveryTime: "25 mins",
          price: "$12",
          image: "image8.jpg",
        },
        {
          name: "Vegetarian Kebab",
          rating: 4.5,
          deals: "15% off on orders over $20",
          deliveryTime: "25 mins",
          price: "$9",
          image: "image9.jpg",
        },
        {
          name: "Chicken Shawarma Kebab",
          rating: 4.9,
          deals: "Free fries with kebab",
          deliveryTime: "25 mins",
          price: "$13",
          image: "image10.jpg",
        },
      ],
    },
    {
      storeName: "Ramen Noodles",
      foodItems: [
        {
          name: "Ramen Noodles",
          rating: 4.8,
          deals: "15% off on orders above $20",
          deliveryTime: "20 mins",
          price: "$11",
          image: "image11.jpg",
        },
        {
          name: "Spicy Ramen",
          rating: 4.7,
          deals: "Free topping with ramen",
          deliveryTime: "20 mins",
          price: "$12",
          image: "image1.jpeg",
        },
        {
          name: "Chicken Ramen",
          rating: 4.9,
          deals: "10% off on your first order",
          deliveryTime: "20 mins",
          price: "$13",
          image: "image2.jpg",
        },
        {
          name: "Vegetable Ramen",
          rating: 4.6,
          deals: "Free drink with ramen",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image3.jpg",
        },
        {
          name: "Miso Ramen",
          rating: 4.5,
          deals: "Free gyoza with ramen",
          deliveryTime: "20 mins",
          price: "$11",
          image: "image4.jpg",
        },
      ],
    },
    {
      storeName: "Biryani",
      foodItems: [
        {
          name: "Biryani",
          rating: 4.6,
          deals: "Free dessert with biryani",
          deliveryTime: "35 mins",
          price: "$14",
          image: "image5.jpg",
        },
        {
          name: "Chicken Biryani",
          rating: 4.8,
          deals: "10% off on weekends",
          deliveryTime: "35 mins",
          price: "$15",
          image: "image6.jpg",
        },
        {
          name: "Vegetable Biryani",
          rating: 4.7,
          deals: "Free raita with biryani",
          deliveryTime: "35 mins",
          price: "$13",
          image: "image7.jpg",
        },
        {
          name: "Mutton Biryani",
          rating: 4.9,
          deals: "15% off on orders above $30",
          deliveryTime: "35 mins",
          price: "$16",
          image: "image8.jpg",
        },
        {
          name: "Egg Biryani",
          rating: 4.5,
          deals: "Free drink with biryani",
          deliveryTime: "35 mins",
          price: "$14",
          image: "image9.jpg",
        },
      ],
    },
    {
      storeName: "Fish and Chips",
      foodItems: [
        {
          name: "Fish and Chips",
          rating: 4.5,
          deals: "10% off on weekdays",
          deliveryTime: "30 mins",
          price: "$13",
          image: "image10.jpg",
        },
        {
          name: "Grilled Fish and Chips",
          rating: 4.7,
          deals: "Free drink with meal",
          deliveryTime: "30 mins",
          price: "$14",
          image: "image11.jpg",
        },
        {
          name: "Crispy Fish and Chips",
          rating: 4.6,
          deals: "Free dessert with meal",
          deliveryTime: "30 mins",
          price: "$12",
          image: "image1.jpeg",
        },
        {
          name: "Spicy Fish and Chips",
          rating: 4.8,
          deals: "15% off on orders above $25",
          deliveryTime: "30 mins",
          price: "$15",
          image: "image2.jpg",
        },
        {
          name: "Fish Taco",
          rating: 4.9,
          deals: "Free fries with taco",
          deliveryTime: "30 mins",
          price: "$11",
          image: "image3.jpg",
        },
      ],
    },
    {
      storeName: "Falafel Wrap",
      foodItems: [
        {
          name: "Falafel Wrap",
          rating: 4.7,
          deals: "Free fries with wrap",
          deliveryTime: "20 mins",
          price: "$9",
          image: "image4.jpg",
        },
        {
          name: "Spicy Falafel Wrap",
          rating: 4.6,
          deals: "10% off on your first order",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image5.jpg",
        },
        {
          name: "Falafel Bowl",
          rating: 4.5,
          deals: "Free drink with bowl",
          deliveryTime: "20 mins",
          price: "$11",
          image: "image6.jpg",
        },
        {
          name: "Falafel Salad",
          rating: 4.8,
          deals: "Free drink with salad",
          deliveryTime: "20 mins",
          price: "$12",
          image: "image7.jpg",
        },
        {
          name: "Veggie Falafel Wrap",
          rating: 4.9,
          deals: "Free side with wrap",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image8.jpg",
        },
      ],
    },
    {
      storeName: "Greek Salad",
      foodItems: [
        {
          name: "Greek Salad",
          rating: 4.6,
          deals: "Free drink with salad",
          deliveryTime: "15 mins",
          price: "$8",
          image: "image9.jpg",
        },
        {
          name: "Chicken Greek Salad",
          rating: 4.8,
          deals: "10% off on your first order",
          deliveryTime: "15 mins",
          price: "$9",
          image: "image10.jpg",
        },
        {
          name: "Mediterranean Salad",
          rating: 4.7,
          deals: "Free dessert with salad",
          deliveryTime: "15 mins",
          price: "$10",
          image: "image11.jpg",
        },
        {
          name: "Falafel Salad",
          rating: 4.9,
          deals: "Free drink with salad",
          deliveryTime: "15 mins",
          price: "$11",
          image: "image1.jpeg",
        },
        {
          name: "Quinoa Greek Salad",
          rating: 4.5,
          deals: "15% off on orders over $20",
          deliveryTime: "15 mins",
          price: "$12",
          image: "image2.jpg",
        },
      ],
    },
    {
      storeName: "Pasta Carbonara",
      foodItems: [
        {
          name: "Pasta Carbonara",
          rating: 4.8,
          deals: "Free garlic bread with pasta",
          deliveryTime: "25 mins",
          price: "$11",
          image: "image3.jpg",
        },
        {
          name: "Pesto Pasta",
          rating: 4.6,
          deals: "10% off on your first order",
          deliveryTime: "25 mins",
          price: "$12",
          image: "image4.jpg",
        },
        {
          name: "Spaghetti Bolognese",
          rating: 4.7,
          deals: "Free drink with pasta",
          deliveryTime: "25 mins",
          price: "$13",
          image: "image5.jpg",
        },
        {
          name: "Alfredo Pasta",
          rating: 4.9,
          deals: "Free dessert with pasta",
          deliveryTime: "25 mins",
          price: "$11",
          image: "image6.jpg",
        },
        {
          name: "Lasagna",
          rating: 4.5,
          deals: "15% off on orders over $30",
          deliveryTime: "25 mins",
          price: "$14",
          image: "image7.jpg",
        },
      ],
    },
    {
      storeName: "Vegetable Stir Fry",
      foodItems: [
        {
          name: "Mixed Vegetable Stir Fry",
          rating: 4.5,
          deals: "15% off on first order",
          deliveryTime: "25 mins",
          price: "$10",
          image: "image2.jpg",
        },
        {
          name: "Tofu Stir Fry",
          rating: 4.3,
          deals: "Free spring rolls with any stir fry",
          deliveryTime: "20 mins",
          price: "$12",
          image: "image3.jpg",
        },
        {
          name: "Broccoli and Carrot Stir Fry",
          rating: 4.7,
          deals: "Buy one, get one 50% off",
          deliveryTime: "30 mins",
          price: "$9",
          image: "image4.jpg",
        },
        {
          name: "Noodle Stir Fry",
          rating: 4.6,
          deals: "Free drink with noodle stir fry",
          deliveryTime: "25 mins",
          price: "$11",
          image: "image5.jpg",
        },
        {
          name: "Mushroom Stir Fry",
          rating: 4.2,
          deals: "10% off on weekends",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image6.jpg",
        },
        {
          name: "Peanut Sauce Stir Fry",
          rating: 4.4,
          deals: "Free dessert with any order",
          deliveryTime: "30 mins",
          price: "$13",
          image: "image7.jpg",
        },
        {
          name: "Spicy Vegetable Stir Fry",
          rating: 4.8,
          deals: "Free upgrade to large size",
          deliveryTime: "20 mins",
          price: "$12",
          image: "image8.jpg",
        },
        {
          name: "Quinoa Vegetable Stir Fry",
          rating: 4.5,
          deals: "20% off on your next order",
          deliveryTime: "30 mins",
          price: "$11",
          image: "image9.jpg",
        },
      ],
    },
    {
      storeName: "Chicken Tikka Masala",
      foodItems: [
        {
          name: "Classic Chicken Tikka Masala",
          rating: 4.9,
          deals: "10% off for first-time customers",
          deliveryTime: "30 mins",
          price: "$15",
          image: "image2.jpg",
        },
        {
          name: "Spicy Chicken Tikka Masala",
          rating: 4.8,
          deals: "Free naan with every order",
          deliveryTime: "25 mins",
          price: "$16",
          image: "image3.jpg",
        },
        {
          name: "Butter Chicken Tikka Masala",
          rating: 4.7,
          deals: "Buy one, get one free on weekends",
          deliveryTime: "30 mins",
          price: "$18",
          image: "image4.jpg",
        },
        {
          name: "Vegetable Tikka Masala",
          rating: 4.6,
          deals: "Free dessert with any order",
          deliveryTime: "20 mins",
          price: "$14",
          image: "image5.jpg",
        },
        {
          name: "Tikka Masala Wrap",
          rating: 4.5,
          deals: "15% off on next order",
          deliveryTime: "30 mins",
          price: "$12",
          image: "image6.jpg",
        },
        {
          name: "Chicken Tikka Masala Bowl",
          rating: 4.8,
          deals: "Free drink with bowl order",
          deliveryTime: "25 mins",
          price: "$17",
          image: "image7.jpg",
        },
        {
          name: "Coconut Chicken Tikka Masala",
          rating: 4.4,
          deals: "10% off for students",
          deliveryTime: "20 mins",
          price: "$16",
          image: "image8.jpg",
        },
        {
          name: "Tikka Masala Pizza",
          rating: 4.3,
          deals: "Free garlic bread with pizza",
          deliveryTime: "30 mins",
          price: "$19",
          image: "image9.jpg",
        },
      ],
    },
    {
      storeName: "Cheeseburger",
      foodItems: [
        {
          name: "Classic Cheeseburger",
          rating: 4.5,
          deals: "Free fries with every burger",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image2.jpg",
        },
        {
          name: "Double Cheeseburger",
          rating: 4.6,
          deals: "10% off on your first order",
          deliveryTime: "25 mins",
          price: "$12",
          image: "image3.jpg",
        },
        {
          name: "Bacon Cheeseburger",
          rating: 4.4,
          deals: "Free drink with burger purchase",
          deliveryTime: "30 mins",
          price: "$11",
          image: "image4.jpg",
        },
        {
          name: "Veggie Cheeseburger",
          rating: 4.7,
          deals: "15% off for vegetarians",
          deliveryTime: "20 mins",
          price: "$10",
          image: "image5.jpg",
        },
        {
          name: "Spicy Cheeseburger",
          rating: 4.3,
          deals: "Free dessert with any order",
          deliveryTime: "30 mins",
          price: "$12",
          image: "image6.jpg",
        },
        {
          name: "Cheeseburger with Avocado",
          rating: 4.5,
          deals: "10% off on weekends",
          deliveryTime: "25 mins",
          price: "$13",
          image: "image7.jpg",
        },
        {
          name: "Cheeseburger Platter",
          rating: 4.8,
          deals: "Free sides with platter",
          deliveryTime: "30 mins",
          price: "$14",
          image: "image8.jpg",
        },
        {
          name: "BBQ Cheeseburger",
          rating: 4.6,
          deals: "Free chips with BBQ burger",
          deliveryTime: "20 mins",
          price: "$13",
          image: "image9.jpg",
        },
      ],
    },
    {
      storeName: "Chocolate Cake",
      foodItems: [
        {
          name: "Classic Chocolate Cake",
          rating: 4.9,
          deals: "10% off on first order",
          deliveryTime: "25 mins",
          price: "$8",
          image: "image2.jpg",
        },
        {
          name: "Chocolate Lava Cake",
          rating: 4.8,
          deals: "Free ice cream with cake",
          deliveryTime: "20 mins",
          price: "$9",
          image: "image3.jpg",
        },
        {
          name: "Chocolate Cheesecake",
          rating: 4.7,
          deals: "15% off for birthday orders",
          deliveryTime: "30 mins",
          price: "$10",
          image: "image4.jpg",
        },
        {
          name: "Dark Chocolate Cake",
          rating: 4.6,
          deals: "Buy one, get one 50% off",
          deliveryTime: "25 mins",
          price: "$12",
          image: "image5.jpg",
        },
        {
          name: "Chocolate Mousse Cake",
          rating: 4.5,
          deals: "Free dessert with any order",
          deliveryTime: "20 mins",
          price: "$11",
          image: "image6.jpg",
        },
        {
          name: "Chocolate Fudge Cake",
          rating: 4.4,
          deals: "10% off on weekends",
          deliveryTime: "30 mins",
          price: "$13",
          image: "image7.jpg",
        },
        {
          name: "Chocolate Raspberry Cake",
          rating: 4.3,
          deals: "Free coffee with cake purchase",
          deliveryTime: "25 mins",
          price: "$14",
          image: "image8.jpg",
        },
        {
          name: "Chocolate Layer Cake",
          rating: 4.2,
          deals: "15% off on your next order",
          deliveryTime: "20 mins",
          price: "$15",
          image: "image9.jpg",
        },
      ],
    },
  ],
};

export default mockdata;
